### ISSUE TITLE
Empty resultset when assessing purposeControl

### ISSUE THREAD

**Issue by meronig** [DITAS-Project/PrivacySecurityEvaluator#13]
For the input:
```json
{
  "requirement": {
				"id": "purposeControlResearch",
				"description": "PurposeControl Research",
				"type": "PurposeControl",
				"properties": {
					"availablePurpose": {
						"unit": "list",
						"value": [
							"research",
							"medical research",
							"nutritional research"
						]
					},
					"allowedGuarantor": {
						"unit": "list",
						"value": ["d63d0e21fdc05f618d55ef306c54af82"]
					}
				} 
  },
  "blueprintAttributes": [
    {
							"id": "purposeControl_research",
							"description": "PurposeControl research",
							"type": "PurposeControl",
							"properties": {
								"availablePurpose": {
									"unit": "list",
									"value": [
										"research",
										"medical research",
										"nutritional research"
									]
								},
								"allowedGuarantor": {
									"unit": "list",
									"value": [
										"d63d0e21fdc05f618d55ef306c54af82"
									]
								}
							}
						}
  ]
}
```

We expect:

```json
{
  "id": "purposeControl_research",
  "description": "PurposeControl research",
  "type": "PurposeControl",
  "properties": {
    "availablePurpose": {
      "unit": "list",
      "value": [
        "research",
        "medical research",
        "nutritional research"
      ]
    },
    "allowedGuarantor": {
      "unit": "list",
      "value": [
        "d63d0e21fdc05f618d55ef306c54af82"
      ]
    }
  }
}
```

Yet, PSE returns an empty resultset

**Comment by meronig** [comment]
The returned resultset is now correct for the given input. Yet, the lists are not correctly compared. For the new input:
`{
  "requirement": {
				"id": "purposeControlResearch",
				"description": "PurposeControl Research",
				"type": "PurposeControl",
				"properties": {
					"availablePurpose": {
						"unit": "list",
						"value": [
							"research",
							"medical research",
							"nutritional research",
							"asdf"
						]
					},
					"allowedGuarantor": {
						"unit": "list",
						"value": ["d63d0e21fdc05f618d55ef306c54af82","abcd"]
					}
				} 
  },
  "blueprintAttributes": [
    {
							"id": "purposeControl_research",
							"description": "PurposeControl research",
							"type": "PurposeControl",
							"properties": {
								"availablePurpose": {
									"unit": "list",
									"value": [
										"research",
										"medical research",
										"nutritional research"
									]
								},
								"allowedGuarantor": {
									"unit": "list",
									"value": [
										"d63d0e21fdc05f618d55ef306c54af82"
									]
								}
							}
						}
  ]
}`

We expect an empty resultset, since the blueprint contains a subset of the items indicated in the lists belonging to the requirements.

**Comment by tawalaya** [comment]
Hi, the current result is somewhat correct. 

First of all the two fields have to be discussed separately. 

The allowedGuarantor field is valid as long as there is at least one match in both lists. 

The availablePurpose fields are the same: as long as the fields overlap it should be included in the result. However, the rank of a blueprint that only contains one match should be lower as the rank of a blueprint that includes two matching fields.

**Comment by meronig** [comment]
Good to know. I was thinking the intersection was not sufficient, and a superset was required. We can then mark the bug as resolved.
