### ISSUE TITLE
JSON parsing error 

### ISSUE THREAD

**Issue by tawalaya** [DITAS-Project/PrivacySecurityEvaluator#28]
Request:
```
{
    "requirement": {
        "id": "encryption_AES128",
        "description": "Encryption AES 128",
        "type": "TransportEncryption",
        "properties": {
            "protocol": {
                "unit": "enum",
                "value": "TLS"
            },
            "algorithm": {
                "unit": "list",
                "value": ["TLS_AES_256_GCM_SHA384", "TLS_AES_128_GCM_SHA256", "TLS_AES_128_CCM_8_SHA256", "TLS_AES_128_CCM_SHA256"]
            },
            "keyLength": {
                "unit": "number",
                "value": 128
            }
        }
    },
    "blueprintAttributes": [{
        "id": "encryption_AES128",
        "description": "Encryption AES 128",
        "type": "TransportEncryption",
        "properties": {
            "protocol": {
                "unit": "enum",
                "value": "TLS"
            },
            "algorithm": {
                "unit": "list",
                "value": ["TLS_AES_256_GCM_SHA384", "TLS_AES_128_GCM_SHA256", "TLS_AES_128_CCM_8_SHA256", "TLS_AES_128_CCM_SHA256"]
            },
            "keyLength": {
                "unit": "number",
                "value": 128
            }
        }
    }]
}
```

Response:
```
{
    "timestamp": "2019-08-07T09:46:27.512+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: de.tub.privacySecurityEvaluator.model.Request[\"requirement\"]->de.tub.privacySecurityEvaluator.model.fields.AlgorithmField[\"value\"])",
    "path": "/v1/filter"
}
```

**Comment by dergeh** [comment]
the algorithm field was from type enum in the last blueprint version has this changed permanently to list?

**Comment by tawalaya** [comment]
Yes part of the last blueprint shema

On Aug 8, 2019 11:20, Durgen <notifications@github.com> wrote:

the algorithm field was from type enum in the last blueprint version has this changed permanently to list?

**Comment by meronig** [comment]
Apparently the issue was fixed in the OSR and IDEKO production environments. However, it is still present in the staging environment (31.171.247.162).

**Comment by meronig** [comment]
I have found out another parsing issue. Here's the information to recreate the bug.
Request:
`{
	"requirement": {
		"id": "purposeControl_research",
		"description": "PurposeControl research",
		"type": "PurposeControl",
		"properties": {
			"availablePurpose": {
				"unit": "list",
				"value": ["research", "medical research", "nutritional research"]
			},
			"allowedGuarantor": {
				"unit": "list",
				"value": ["d63d0e21fdc05f618d55ef306c54af82"]
			}
		}
	},
	"blueprintAttributes": [{
		"id": "purposeControl_research",
		"description": "PurposeControl research",
		"type": "PurposeControl",
		"properties": {
			"availablePurpose": {
				"unit": "list",
				"value": ["research", "medical research", "nutritional research"]
			},
			"allowedGuarantor": {
				"unit": "list",
				"value": ["d63d0e21fdc05f618d55ef306c54af82"]
			}
		}
	}]
}`

Response:
`{
    "timestamp": "2019-08-09T14:45:14.266+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: Cannot deserialize instance of `java.util.HashMap` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.HashMap` out of START_ARRAY token\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: de.tub.privacySecurityEvaluator.model.Request[\"requirement\"]->de.tub.privacySecurityEvaluator.util.FakeGraph[\"value\"])",
    "path": "/v1/filter"
}`
